version: '3'
networks:
  laravel:
  app-shared:
    driver: bridge
services:
  nginx:
    image: nginx:stable-alpine
    container_name: tails_admin
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
      - app-shared
  mysql:
    image: mysql:5.7.22
    container_name: mysql_one
    restart: unless-stopped
    tty: true
    ports:
      - "9906:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE : tails_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: oui
      MYSQL_ROOT_PASSWORD : oui
    networks:
      - laravel
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_one
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
      - app-shared
  composer:
    image: composer:latest
    container_name: composer_one
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  npm:
    image: node:18.12
    container_name: npm_one
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan_one
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - laravel