version: '3'
networks:
  laravel:
  tails_admin_app-shared:
    external: true
services:
  nginx:
    image: nginx:stable-alpine
    container_name: tails_user
    ports:
      - "8080:80"
    volumes:
      - ./src/TailsCosmectics:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
      - tails_admin_app-shared
  mysql:
    image: mysql:5.7.22
    container_name: mysql_two
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE : tails_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: oui
      MYSQL_ROOT_PASSWORD : oui
    networks:
      - laravel
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_two
    volumes:
      - ./src/TailsCosmectics:/var/www/html
    networks:
      - laravel
      - tails_admin_app-shared
  composer:
    image: composer:latest
    container_name: composer_two
    volumes:
      - ./src/TailsCosmectics:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  npm:
    image: node:18.12
    container_name: npm_two
    volumes: 
      - ./src/TailsCosmectics:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan_two
    volumes:
      - ./src/TailsCosmectics:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel